version: '3.8'

services:
  vue-app:
    build:
      context: .
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 on the container
    volumes:
      - .:/app
      - /app/node_modules  # Prevent issues with node_modules overwriting
    environment:
      - NODE_ENV=production
